finished QA system
MikedeJong14/studenten-portaal pull request #2
Opened 2021-01-08 11:14 UTC by RutgerVos

2021-01-08 11:28 UTC, 99051257 approved these changes
Very good! Don't forget to get rid of comments that aren't needed anymore, though.

2021-01-08 13:47 UTC, MikedeJong14 requested changes
Heb wat comments achtergelaten bij stukjes code die nog verbeterd kunnen worden.
Verder is het wel in orde

2021-01-08 13:47 UTC, MikedeJong14 commented on resources/views/createQuestion.blade.php
> +            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
Deze drie DIVs zijn niet afgesloten

2021-01-08 13:47 UTC, MikedeJong14 commented on resources/views/livewire/questions.blade.php
> +        <script>
Dit stuk code is erg moeilijk om te begrijpen, de tab inspringing is erg apart. Is beter om dat wat duidelijker te maken zodat we beter kunnen zien welke div wat bevat en waar precies de divs worden afgesloten

2021-01-08 13:47 UTC, MikedeJong14 commented on resources/views/Q&A.blade.php
> +            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
Regel 24, 25 en 26 DIVs zijn niet afgesloten met /div

2021-01-08 13:47 UTC, MikedeJong14 commented on resources/views/navigation-dropdown.blade.php
> +            <x-jet-responsive-nav-link href="{{ url('/ask-Question') }}" :active="request()->is('ask-Question')">
Kan je misschien toelichten waarom alle route() naar url() is veranderd?

2021-01-08 13:47 UTC, MikedeJong14 commented on resources/views/updateQuestion.blade.php
> +            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
Hetzelfde als createQuestion.blade.php, onafgesloten DIVs

2021-01-08 13:47 UTC, MikedeJong14 commented on routes/web.php
>  Route::middleware(['auth:sanctum', 'verified'])->get('/planning/appointment/{id}', [PlanningController::class, 'show']);
Is misschien gelijk een goede kans om 'Route Groups' te gebruiken. zorgt ervoor dat er een groep bestaat voor de middleware die hier wordt gebruikt
https://laravel.com/docs/8.x/routing#route-groups

2021-01-12 12:13 UTC, MikedeJong14 approved these changes
Ziet er goed uit! Dankuwel

2021-01-12 12:15 UTC, merged